# Generated by Django 3.2.12 on 2022-08-14 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stundent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('course', models.CharField(max_length=140)),
                ('rating', models.IntegerField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
